enderbow:
  usepearl: true
locale:
  noperm: '&4You do not have permission for that!'
  invalidplayer: '&4That is not a valid player!'
  onlyplayers: '&4YOnly players can enter that command!'
  giveenderbow: '&2Gave enderbow to %PLAYER%!'
  reload: '&2[Enderbow Config Reloaded]'
